FACTOR
  /VARIABLES Agr Min Man PS Con SI Fin SPS TC
  /MISSING LISTWISE
  /ANALYSIS Agr Min Man PS Con SI Fin SPS TC
  /PRINT INITIAL EXTRACTION
  /PLOT EIGEN
  /CRITERIA MINEIGEN(1) ITERATE(25)
  /EXTRACTION PC
  /ROTATION NOROTATE
  /SAVE REG(ALL)
  /METHOD=COVARIANCE.


GRAPH
  /SCATTERPLOT(BIVAR)=FAC1_3 WITH FAC2_3
  /MISSING=LISTWISE.
